data:
  raw_path: "./data/raw/"
  results_path: "./data/results/"
  models_path: "./models/"

preprocessing:
  detect_outliers:
    column: "item_price"
    iqr_factor: 1.5
    z_threshold: 3
    lower_percentile: 0.01
    upper_percentile: 0.99

model:
  types:  # Lista de modelos disponibles
    - "random_forest"
    - "xgboost"
    - "arima"
    - "exponential_smoothing"
  selected: "xgboost"  # Modelo seleccionado para entrenamiento
  hyperparameters:
    random_forest:
      n_estimators: 100
      random_state: 42
      max_depth: 3
    xgboost:
      n_estimators: 100
      random_state: 42
      max_depth: 3
      learning_rate: 0.1
    arima:
      order: [5,1,0]  # Parámetros p,d,q
    exponential_smoothing:
      seasonal: "add"
      seasonal_periods: 12

output:
  cleaned_data_filename: "./data/output/data_cleaning.csv"
  engineered_data_filename: "./data/output/data_engineering.csv"
  predictions_data_filename: "./data/output/data_predictions.csv"
  model_features_filename: "./models/model_features.txt"

flags:
  force_cleaning: false
  force_engineering: false
  force_training: false
